name: DevSecOps Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main ]

jobs:
  # --- ÉTAPE 1 : BUILD ---
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l'image Docker
        run: docker build -t vuln-app:${{ github.sha }} .

      - name: Sauvegarde de l'image (pour les jobs suivants)
        run: docker save vuln-app:${{ github.sha }} > image.tar

      - name: Stockage de l'artefact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  # --- ÉTAPE 2 : SAST (Analyse Statique) ---
  sast:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Scan Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
            p/owasp-top-ten

  # --- ÉTAPE 3 : SCA (Analyse des Dépendances) ---
  sca:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Audit des vulnérabilités NPM
        run: |
          cd src
          npm install
          npm audit --audit-level=high 
          # --audit-level=high fait échouer le build si vulnérabilités High ou Critical

  # --- ÉTAPE 4 : CONTAINER SCAN (Scan de l'image) ---
  container_security:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Téléchargement de l'image buildée
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Chargement de l'image dans Docker
        run: docker load -i image.tar

      - name: Scan Trivy (Vérification OS et Libs)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vuln-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1' # CRITIQUE : Bloque le pipeline si des failles sont trouvées
          severity: 'CRITICAL,HIGH'